### ISSUE TITLE
No "nodes" in the cluster and experiment does not "build"

### ISSUE THREAD

**Issue by VitaliKaiser** [polyaxon/polyaxon#55]
Hi,

We have a kubernetes setup on Google Cloud and it´s seems we did everything correctly (no warnings or errors). After depolying polyaxon we get
```
1. Get the application URL by running these commands:
    export POLYAXON_IP=*******
    export POLYAXON_HTTP_PORT=*******
    export POLYAXON_WS_PORT=*******

    echo http://$POLYAXON_IP:$POLYAXON_HTTP_PORT

2. Setup your cli by running theses commands:

  polyaxon config set --host=$POLYAXON_IP --http_port=$POLYAXON_HTTP_PORT  --ws_port=$POLYAXON_WS_PORT


3. Log in with superuser

  USER: root
  PASSWORD: *******
```

But when trying out the simple example I notice there are no nodes visible:

```
> polyaxon cluster

Cluster info:

--------------  ----------------------------------------
build_date      2018-01-31T22:30:55Z
major           1
go_version      go1.9.2b4
git_version     v1.9.2-gke.1
platform        linux/amd64
git_commit      4ce7af72d8d343ea2f7680348852db641ff573af
git_tree_state  clean
minor           9+
compiler        gc
--------------  ----------------------------------------

```

And after submitting a job, the job does not execute and remains at "building".

Do you have maybe a hint, what´s going wrong?

Thanks.
Vitali

**Comment by mouradmourafiq** [comment]
Hi @VitaliKaiser 

For the first issue it could be related to this [issue](#50), it's already fixed and will be part of the next release.

For the second, can you confirm that if you submit a second job the experiment build and starts?

I am making a release this weekend, most of these issues were addressed.

**Comment by VitaliKaiser** [comment]
Hi M,

thanks, that sounds great. 
For the second, how do I submit a second job? If I type in `polyaxon run` a new experiment is started. And all of them stuck in "building". And it says there are 0 jobs. 

Best,
Vitali

**Comment by jrozansk** [comment]
@VitaliKaiser 

I am not sure what problem you are facing. We don't know what happened underneath but...
Symptoms looks similar so please apply workaround from this issue and verify whether it helps:
https://github.com/polyaxon/polyaxon-chart/issues/2

**Comment by VitaliKaiser** [comment]
Hi,

so tried to redeploy polyaxon today - but none of my two problems got solved :)
I am pretty much a kubernetes and helm noob, but I guess the reason is there was no update on the https://charts.polyaxon.com repo. (The `polyaxon cluster` command gives me still the same version numbers).
I would love to build the newest commits and maybe even contribute at a certain point, but at the moment I am struggling how to install the current github version on my cluster.

@jrozansk Thanks for the link. Again I would love to try this solution but I have no idea how to install the polyaxon-charts repo 🙈 

Maybe you can add a small documentation for guys like me: something like 'how to get the dev version running'. Alternatively, I would love to hear from you guys after the new release is published. 

Best,
Vitali

**Comment by mouradmourafiq** [comment]
Hi @VitaliKaiser, to use the last version, you can run `helm update`.

Let me know if you have any problem, I can assist you.

**Comment by VitaliKaiser** [comment]
Problem seems to be solved in the new polyaxon version (0.5)! Thanks :)
